//@version=6
indicator(title="Overlay")

// RSI
i1=input(title='Relative Strength Indicator (RSI)',defval=true)
TC=ta.change(close)
SM(_p,_l)=>
    _s=0.0
    for i=0 to _l-1
        _s+=_p[i]/_l
RM(_p)=>
	_a=float(1)/7, _s=0.0, _s:=na(_s[1])?SM(_p,7):_a*_p+(1-_a)*nz(_s[1])
R=100-100/(1+RM(TC>=0?TC:0)/RM(TC<0?-TC:0))
plot(i1?R:na,color=#ffffff), hline(i1?70:na), hline(i1?30:na)

// Stochastic
i2=input(title='Stochastic',defval=true)
_2l=input.int(7,title="Stochastic Length")
L=ta.lowest(low,_2l)
K=(close-L)/(ta.highest(high,_2l)-L)*100
plot(i2?K:na)
plot(i2?SM(K,3):na,color=d)
hline(i2?80:na)
hline(i2?20:na)

// Plot bearish divergence
plot(ph ? R[5] : na,offset = -5,color = (high[5] > prevHigh5 and R[5] < prevRHigh and i_ph and ph and i3) ? #ff0000 : color.new(#ffffff,100),linewidth = 2)

// Directional Movement Index
i4=input(title='Directional Movement Index',defval=false)
up=ta.change(high)
down=-ta.change(low)
trur=ta.rma(ta.tr,14)
plus=fixnan(100*RM(na(up)?na:up>down and up>0?up:0)/trur)
minus=fixnan(100*RM(na(down)?na:down>up and down>0?down:0)/trur)
sum=plus+minus
plot(i4?100*RM(math.abs(plus-minus)/(sum==0?1:sum)):na,color=#F50057)
plot(i4?plus:na,color=#2962FF)
plot(i4?minus:na,color=#FF6D00)
