//@version=6
indicator(title="Overlay")

// RSI
i1 = input(title='Relative Strength Indicator (RSI)', defval=true)
SM(_p,_l)=>
    _s=0.0
    for i=0 to _l-1
        _s+=_p[i]/_l

RM(_p)=>
    rs = SM(_p,7), _a = float(1)/7, _s=0.0, _s:=na(_s[1])?rs:_a*_p+(1-_a)*nz(_s[1])
TC=ta.change(close), R=100-100/(1+RM(TC>=0?TC:0)/RM(TC<0?-TC:0))
plot(i1?R:na,color=#ffffff), hline(i1?70:na), hline(i1?30:na)

// Stochastic
i2 = input(title='Stochastic',defval=true)
L = ta.lowest(low, 7), K = (close-L)/(ta.highest(high, 7)-L)*100
plot(i2?K:na), plot(i2?SM(K,3):na,color=#ffff00), hline(i2?80:na), hline(i2?20:na)

// Directional Movement Index
i4 = input(title='Directional Movement Index',defval=false)
u = ta.change(high), d = -ta.change(low), t = ta.rma(ta.tr,14), p = fixnan(100*RM(na(u)?na:u>d and u>0?u:0)/t), m = fixnan(100*RM(na(d)?na:d>u and d>0?d:0)/t), sum=p+m
plot(i4?100*RM(math.abs(p-m)/(sum==0?1:sum)):na,color=#F50057), plot(i4?p:na,color=#2962FF), plot(i4?m:na,color=#FF6D00)
